---
- name: Update systemd
  dnf:
    name: systemd 
    state: latest
  notify:
    - Restart systemd

- name: Update host
  dnf:
    name: "*"
    state: latest

- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: epel-release
    state: latest
