---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-deployment-infra
  labels:
    app: vault-deployment-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-infra
  template:
    metadata:
      labels:
        app: vault-infra
    spec:
      containers:
      - name: vault-infra
        image: docker.io/hashicorp/vault:1.6.2
        env:
          - name: "VAULT_DEV_ROOT_TOKEN_ID"
            value: "secrettokeninfra"
          - name: "VAULT_DISABLE_MLOCK"
            value: "true"
          - name: "SKIP_CHOWN"
            value: "true"
          - name: "SKIP_SETCAP"
            value: "true"
        ports:
          - containerPort: 8200
            protocol: TCP
            hostPort: 8100
